version: '3'
services:
  backend:
     build: "./"
     restart: always
     container_name: deliver-app
     labels:
       logging: "promtail"
       logging_jobname: "containerlogs"
     ports:
        - "4040:4040"
     networks:
       - app
networks:
  app:
    external: true